apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-chatbot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chatbot
  template:
    metadata:
      labels:
        app: chatbot
    spec:
      containers:
      - name: flask-chatbot
        image: raghavboi/flask-chatbot  # change if using local image
        ports:
        - containerPort: 8088
