apiVersion: v1
kind: Service
metadata:
  name: chatbot-service
spec:
  type: NodePort
  selector:
    app: chatbot
  ports:
  - port: 80
    targetPort: 8088
    nodePort: 30088  # You can visit this on localhost:30088
