version: "3.8"
services:
  jenkins:
    image: jenkins/jenkins:lts
    user: root            # so it can install Docker CLI
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080"
      - "50000:50000"     # for JNLP agents
